### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by kle-dev** [mui-org/material-ui-pickers#1786]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    4.0.0-alpha.7     |
| material-ui          |   4.9.14      |
| React                |   16.12.0      |
| Chrome, Safari, Sandbox               |   not depending on browser      |
| moment         |   2.25.3      |  |

## Steps to reproduce

1. Use `<StrictMode> ... </StrictMode>` in `App.js`
2. place your `LocalizationProvider` and `DateRangePicker` or `MobileDateRangePicker` or `DesktopDateRangePicker` inside
3. click to choose a date
4. get error message bellow in console

## Expected behavior

Not showing this error message:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Transition)
    in Transition (created by ForwardRef(Fade))
    in ForwardRef(Fade) (created by ForwardRef(Backdrop))
    in ForwardRef(Backdrop) (created by WithStyles(ForwardRef(Backdrop)))
    in WithStyles(ForwardRef(Backdrop)) (created by ForwardRef(Modal))
    in div (created by ForwardRef(Modal))
    in ForwardRef(Portal) (created by ForwardRef(Modal))
    in ForwardRef(Modal) (created by ForwardRef(Dialog))
    in ForwardRef(Dialog) (created by WithStyles(ForwardRef(Dialog)))
    in WithStyles(ForwardRef(Dialog)) (created by ModalDialog)
    in ModalDialog (created by MobileWrapper)
    in MobileWrapper (created by WrapperComponent)
    in WrapperComponent (created by RangePickerWithStateAndWrapper)
    in RangePickerWithStateAndWrapper (created by ForwardRef)
    in ForwardRef (at App.js:17)
    in LocalizationProvider (at App.js:16)
    in StrictMode (at App.js:15)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)
```

## Actual behavior
 
Showing the error message above

## Live example

https://codesandbox.io/s/new-sunset-j9m4d?file=/src/App.js

**Comment by klever-dev** [comment]
@oliviertassinari where is the duplicate ? i couldn't  find one, sorry

**Comment by klever-dev** [comment]
@oliviertassinari where is the duplicate ? i couldn't find one, sorry

**Comment by kle-dev** [comment]
@oliviertassinari where is the duplicate ? i couldn't find one, sorry

**Comment by oliviertassinari** [comment]
Duplicate of https://github.com/mui-org/material-ui/issues/13394

**Comment by katyapavlenko** [comment]
hi! Met this problem in my project
its a duplication of  mui-org/material-ui#13394, but solution from there did not help me with pickers
I used `"@material-ui/core": "^5.0.0-alpha.6",` and it helped with all material components, but not with pickers

Do you have any ideas how can I fix it specificly for pickers?

**Comment by dmtrKovalenko** [comment]
@katyapavlenko no way. Wait for @material-ui/core update the `react-transition-group` :)

**Comment by katyapavlenko** [comment]
but what should I do until it happens?

**Comment by dmtrKovalenko** [comment]
Do not wrap in strict mode

**Comment by oliviertassinari** [comment]
The issue was already solved in @material-ui/core@v5.0.0-alpha.10. Do we have a reproduction with the latest version?

**Comment by katyapavlenko** [comment]
@oliviertassinari I tried v5.0.0-alpha.10 today, it did not help

**Comment by oliviertassinari** [comment]
@katyapavlenko It's solved: https://codesandbox.io/s/objective-hawking-zfv1x.

**Comment by vishidabas** [comment]
@oliviertassinari this issue still persist. if you check the console for above codesandbox example when you click on arrows to move months.
